//UART
#define BUFFER_SIZE 64

//I2C
#define NUCLEO_I2C_SDA_PIN 10
#define NUCLEO_I2C_SCL_PIN 11

//LDO
#define NUCLEO_LDO_VGEN
//DAC

//RELAY
#define NUCLEO_RELAY_EN
//PWM

//R_ADJ
#define NUCLEO_RADJ_1V8
#define NUCLEO_RADJ_2V1
#define NUCLEO_RADJ_2V3
#define NUCLEO_RADJ_2V5

//CURRENT SENSOR
#define NUCLEO_CURRENT_VIOUT

//CHIP PROTECTOR
#define NUCLEO_CHIP_EN
#define NUCLEO_CHIP_RX
#define NUCLEO_CHIP_TX
